name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-one: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
